---
- name: Gather minimal facts
  ansible.builtin.setup:
    gather_subset:
      - min

- block:
  - name: Install podman
    ansible.builtin.yum:
      name: podman
      state: present
      enablerepo: rhel-7-server-extras-rpms

  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

- block:
    - name: Enable container-tools module
      ansible.builtin.yum:
        name: container-tools
        state: present
        enablerepo: rhel-8-for-x86_64-baseos-rpms
  
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8'

- block:
  - name: Install Podman
    ansible.builtin.yum:
      name: podman
      state: present

  when: ansible_distribution in ['AlmaLinux', 'CentOS']

- block:
  - name: Install Podman
    ansible.builtin.apt:
      name: podman
      state: present

  when: ansible_os_family == 'Debian'
